### PR TITLE
edits

### PR DESCRIPTION
**Pull request by scookingkid**

### CODE REVIEW

**Comment by leebock** [comment]
Hi!  Can you give me a little background about this request?  Are you intending for these changes to be incorporated into the primary repo?  Thanks!

**Comment by scookingkid** [comment]
Hi,

I apologize for that, I’m in the process of learning github and I was kind of just messing around with it cause the application looks really cool. You can just disregard the request, I couldn’t figure out how to delete it.

Thank you,

***@***.***
Shannon Clough​​​​

GIS Specialist I
office 919. 361. 5000<tel:919.%20361.%205000>
***@***.******@***.***>
621 Hillsborough Street, Suite 500
​Raleigh, NC 27603
www.<https://mcadamsco.com/>mcadamsco.com<https://mcadamsco.com/>
Join Our Team<https://mcadamsco.com/careers/>
***@***.***<https://www.linkedin.com/company/the-john-r--mcadams-company>
***@***.***<https://www.instagram.com/mcadamsco/>

**Comment by leebock** [comment]
Hi Shannon!

All good!  Phew, for a minute there, I thought I was going to have to merge a pull request (something with which I personally have little experience).

If you have questions about making a Treasure Hunt, I’m happy to answer questions.  You can reach me at ***@***.******@***.***>.

All the best!

Lee Bock

**Comment by leebock** [comment]
Closing.  Contributor reports that pull request can be disregarded.

**Pull request closed without merging**
